baseurl: "https://blog.maovlog.com"
languageCode: "zh-cn"
title: "老陳网志"
theme: "hugo-tania"
paginate: 10

#disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: Logo.png
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "手帳 &ノート"
  siteDesc: "手帳 &ノート"
  author: "老陳"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email:
    facebook:
    github:
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: true
    provider: twikoo

    twikoo:
        id: https://twikoo.chenplus.com
        # 默认 ap-shanghai
        region:
        # 默认 window.location.pathname
        path:
        # 默认 zh-CN
        lang:  

menu:
  header:
    - name: 标签
      url: "/tags/"
    - name: 归档
      url: "/articles/"
    - name: 关于
      url: "/about/"  
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
